# index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

ListProperties:
    path: /List
    controller: App\Controller\ListProperties::index

property.show:
    path: /biens/{slug}-{id}
    controller: App\Controller\ListProperties::show
    requirements: 
        slug: "[a-z0-9\\-]*"

admin.property.show:
    path: /adminlist
    controller: App\Controller\Admin\AdminPropertyController::index

admin.property.edit:
    path: /adminlist/{id}/edit
    controller: App\Controller\Admin\AdminPropertyController::edit

admin.property.new:
    path: /adminlist/new
    controller: App\Controller\Admin\AdminPropertyController::create

admin.property.delete:
    path: /adminlist/{id}/delete
    controller: App\Controller\Admin\AdminPropertyController::delete

login:
    path: /login
    controller: App\Controller\security\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\security\SecurityController::logout