# index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

ListProperties:
    path: /List
    controller: App\Controller\ListProperties::index
