# index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

ListProperties:
    path: /List
    controller: App\Controller\ListProperties::index

property.show:
    path: /biens/{slug}-{id}
    controller: App\Controller\ListProperties::show
    requirements: 
        slug: "[a-z0-9\\-]*"